### ISSUE TITLE
Pragma foreign_keys does not enable foreign key support

### ISSUE THREAD

**Issue by MrCanadianMenace** [GULPF/tiny_sqlite#10]
When I run
```Nim
db.exec("PRAGMA foreign_keys;")
```
A row with just 0 is returned

When I run
```Nim
db.exec("PRAGMA foreign_keys = ON;")
db.exec("PRAGMA foreign_keys;")
```
A row with just 1 is returned, but I am still able to perform insertions which should be raising foreign key constraint errors.  The cascade deletes I have setup also are not executed when I delete a referenced row.

**Comment by GULPF** [comment]
Can you give a complete test case? I cannot reproduce this. Note that turning on foreign keys only turns it on for that db connection, so if you create another db connection you need to turn it on again. I'll probably make a change so that the `openDatabase` proc turns foreign keys on by default to make things easier.

**Comment by GULPF** [comment]
Can you give a complete test case? I cannot reproduce this. Note that turning on foreign keys only turns it on for that db connection, so if you create another db connection you need to turn it on again. I'll probably make a change so that the `openDatabase` proc turns foreign keys on by default to make things easier.

**Comment by GULPF** [comment]
Foreign key constraints are now enabled by default and I cannot reproduce any issues with it.
